default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['DATABASE_HOST'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  username: <%= ENV['DATABASE_USER'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000

development:
  <<: *default
  database: chores_development

test:
  <<: *default
  database: chores_test

production:
  <<: *default
  database: chore_production
